# Configuration File for Project Plugin by Melonthedev & Stebadon
# McSurvivalprojekt.de

# Constants
projectName: Survivalprojekt 7.0
projectType: Survival SMP
showProjectType: false
discordInvite: discord.gg/AmskHwQSCT

# Start with /survivalprojekt startProject
projectActive: false

# In spawn area players can't place or break blocks, take damage, damage entities, etc.
spawn:
  world: world
  radius: 20 # Spawn radius (in blocks)
  border_width: 40 # Diameter of border existing before project starts (in blocks)

config:
  disabledcommands:
    status: false # true if command should be disabled. works for every command
  # /toggleendaccessibility
  endaccessible: true
  # /logoutput
  logging: normal
  actionBarSpawnMessages:
    enabled: true
  customTabListInfo:
    enabled: true
  eastereggDamage:
    enabled: true
  spectateStebadonEasteregg:
    enabled: false
  customJoinMessages:
    enabled: true
    usePlayerNameWithStatus: false
  customQuitMessages:
    enabled: true
  newPlayerWelcomeMessage:
    enabled: true
    message: §l§a%playerName%, Herzlich Willkommen auf Survivalprojekt!
  afkSystem:
    enabled: true
    timeoutInMinutes: 10
  customServerMotds:
    enabled: true
    showServerInfos: true
  deathLocationCommand:
    enabled: false
  skippablePvpCooldown:
    enabled: true
  blockElytraEnchantments:
    enabled: false
  customRecipes:
    enabled: true
    invisibleItemFrame: true

countdowntime: 10
extraText: "Have Fun"
worldborderSize: 59999968
pvpCooldownTime: 3

startcommand: [
  "showProjectname",
  "startCountdown",
  "shrinkenWorldborder",
  "expandWorldborder",
  "resetFood",
  "resetHealth",
  "blockEndAccess",
  "resetTime",
  "resetPvpCooldowns",
  "resetTotalWorldTime",
  "showExtra",
]
# /hardcore
hardcore:
  enabled: false
  giantDeathTitle: false
  blockSpectatorTeleport: true

# /lifesteal
lifesteal:
  enabled: false
  blocknetherite: true
  blockelytra: true
  blocktotems: true
  hearts: {}
  defaultheartcount: 10
  revivedPlayerHeartCount: 1

# Entries: uuid: remainingMinutes
pvpCooldown: {}

# Donators of Survivalprojekt (Unterstuetzer)
# Entries: uuid: true/false
donators:
  425723a9-6817-4afc-8566-dab11a88e1de: true #Melonthedev
  ec95ea3b-83b2-49af-aaa9-247ec876b9e8: true #Stebadon
  eda01caf-cdc4-4be0-856a-f8b8bbec2560: true #Sprengmeister444
  774cae75-594b-4c47-b872-0ed504c0d64d: true #Soro
  13b65170-0e29-4e6b-961e-c4643bfc08f9: true #Jonbadon
  #dedaa175-6e4e-4ae0-b8d4-5a366838073d: true #El_Crafter
  58faaa81-7df2-4645-8708-44ccb63bbddd: true #Progeto
  #00ad0b76-9173-481e-9a1e-804e1245d8c3: true #TheAquaBaron
  ce96dc7b-22ce-49d3-9da0-50dd9eef19fe: true #Luca900
  700fc5e7-e7bf-4131-a6b4-16f234616103: true #ImbaOverlord
  65e2d822-3fb7-4d6b-99d4-654204d24a67: true #L18n
  a7a6dbe4-0a51-4c5a-a16a-05ac449b106a: true #LuckyRich28
  b7bf9422-8d34-4635-9114-579195f2f951: true #Tantal0s

# Custom joinmessages which will be randomly displayed whenever a player joins
# use %playerName% as placeholder for the playername
# please use only minimessage formatting e.g. <red> or <rainbow>
joinmessages: [
                "%playerName% sagt hallo",
                "%playerName% ist back",
                "%playerName% ist wieder da",
                "<bold><red>*BOOM* </red></bold>%playerName%<bold><red> *BOOM*</red></bold> ist jetzt online",
                "%playerName% ist hier, um heimlich die Goldfarm zu nutzen",
                "Ein wildes %playerName% ist aufgetaucht",
                "Knock Knock, %playerName% ist da",
                "Servus, ich bin's, %playerName%",
                "Die Legende %playerName% ist wieder da",
                "PvP-Profi %playerName% ist online",
                "%playerName% ist nur wegen den guten Joinmessages hier :)",
                "%playerName% hat den weg in's Paradies gefunden",
                "%playerName% beachtet die Regeln heute besonders gut",
                "%playerName% ist online, um die wunderschöne <gold>Spawninsel</gold> von Jonbadon und Soro zu bewundern",

    #"ist nun online und bleibt das auch hoffentlich",
    #"hat sich wiedereinmal hierher verirrt",
    #"ist jetzt hier und will nicht sterben",
    #"hat sich verklickt aber bleibt",
    #"ist nur online um seine Farm zu leeren",
    #"ist auf den Server gehoppst",
    #"ist jetzt online und will nicht sterben",
    #"wollte eigentlich nicht hier sein aber ist jetzt online"
]

# Custom quitmessages which will be randomly displayed whenever a player joins
# use %playerName% as placeholder for the playername
# please use only minimessage formatting e.g. <red> or <rainbow>
quitmessages: [
                "%playerName% ist vor Jonbadon geflohen",
                "%playerName% hat den Server verlassen, um Tantal0s zu entkommen",
                "%playerName% hat mal lieber gecombat-logged",
                "%playerName% wurde zum Essen gerufen",
                "%playerName%'s <gold>Chicken Nuggets</gold> verbrennen!!!",
                "%playerName% hat genug von den Joinmessages :(",
                "%playerName%'s Mutter hat den Stecker gezogen",
                "%playerName%'s PC hat sich selbst zerstört",
                "%playerName% wusste nicht, was <red>Alt+F4</red> macht",
                "%playerName% macht nen ragequit",
                "%playerName% hat sich in die reale Welt zurückgezogen",
                "%playerName% ist von uns gegangen",
                "Boah, endlich ist %playerName% weg",
                "Tschüss, %playerName%!",
                "Ich hab %playerName% mal gekickt xD",
                "Bis Baldrian, %playerName%!",
                "Landesgarten<b>tschau</b>, %playerName%!",
                "%playerName% hat die Picke abgegeben",
                "%playerName% wurde vom <light_purple>Enderman</light_purple> gekidnappt",
                "%playerName% ist <red>OutOfMemory</red>",
                "<red>Error <b>404</b>:</red> Player %playerName% not found",
]

# Actionbar messages which will be displayed whenever a player is in the spawn area
# please use only minimessage formatting e.g. <red> or <rainbow>
actionbarmessages: [
  "<gray>Drücke <white><key:key.sneak></white> um von dieser Insel zu gleiten",
  "<gray>Chatte mit <white>\\<rainbow></white> um RGB zu schreiben",
  "<gray>Benutze <white>/status</white> um einen Status zu setzen",
  "<gray>Benutze <white>/r</white> um auf eine Privatnachricht zu antworten",
  "<gray>Benutze <white>/msg</white> um Nachrichten sogar an offline Spieler zu senden",
  # LIFESTEAL INFOS
  #- <gray>Benutze <white>/withdraw</white> um Herzen in Items umzuwandeln
  #- <gray>Unter dem Namen eines Spielers sieht man dessen <white>Lifesteal Herzen</white> Anzahl
  #- <gray>Wenn du stirbst verlierst du permanent <white>1 Herz!</white>
  #- <gray>Wenn du keine Herzen mehr hast, <white>wirst du gebannt!</white>
  #- <gray>Benutze <white>/skipPvpCooldown</white> um deinen PvP Cooldown zu überspringen
  #- <gray>Du bekommst permanente Herzen, <white>wenn du Spieler tötest</white>
]

# Custom MOTDs (MessageOfTheDay) which can be seen in the server list
# use %randomPlayer% as placeholder for a random playername
# use %randomOnlinePlayer% as placeholder for a random playername of an online player
# use
# please use only minimessage formatting e.g. <red> or <rainbow>
motds: [
    "Nico baut wieder verbotene Symbole",
    "Todescount-Duell: stebadon vs jonbadon",
    "Tantalos grieft wieder",
    "Das Problem mit dem Zipfel",
    "Dann müssen wir ihn sehr schmal und eng machen",
    "is das eig auch ein MODT?",
    "Und wollen wir ihn weiß machen???",
    "Junge der Typ ist ne Maschine",
    "Oh",
    "Sind uns die Zipfel groß genug?",
    "Ja",
    "Das Teil ist einfach zu lang",
    "HALT STOP",
    "und das?",
    "JAAAAAAAAAAAAAAAAAAAA",
    "Das sieht aus wie ne Rakete",
    "Du hast dich doch beschwert, dass er zu klein ist - Soro",
    "Was hast du gegen Steine?!",
    "Irgendwo hab ich grade rengeschissen...",
    "Ich weiß, aber ich weiß nicht...",
    "Ja, kann ich nicht nein sagen",
    "Holy Spawner I"


    #"GUYS MOTD TIME",
    #"Auch anständige?",
    #"Tantal0s ist wieder am griefen",
    #"MelonClient ist scheiße - Jonbadon",
    #"wieder mal die alten?",
    #"Joris ist klein",
    #"Mobbing in den MOTD's?",
    #"Ja",
    #"Gerne",
    #"Kann ich machen - Tantal0s",
    #"Aber ich will hier nd eherenlos werden",
    #"MOTD Channel: ALLES wird genommen",
    #"imagine man liked seine eigenen vorschläge",
    #"Sorry, zu lang für sie",
    #"Also die Serverliste",
    #"schade",
    #"aber eig random genug",
    #"Tantalos für die mündliche 1 in Geschi???",
    #"Lancelot ist mal wieder AFK",
    #"Die Qualität dieser MOTD's, 1A",
    #"Kritisch...",
    #"aber wahr",
    #"Joris sucht immer noch sein Pigstep",
    #"Das ist doch geil!",
    #"Steffen ist schon tot",
    #"und hat es verdient",
    #"Findet schnitzelbrötchen besser als Freunde",
    "https://youtu.be/dQw4w9WgXcQ" # NICHT ANRÜHREN!!!
]
