name: ProjectPlugin
version: '${project.version}'
main: wtf.melonthedev.projectplugin.Main
api-version: 1.18
authors: [ Melonthedev, Avocado ]
description: A little plugin for our project :)
website: melonthedev.wtf

commands:
  status:
    description: Setzt deinen persönlichen Status
  #votekick:
  #  description: Votekick Command
  #lockchest:
  #  description: LockChest Command
  position:
    description: Positionen in der Welt privat und öffentlich speichern
    aliases:
      - pos
  colorcodes:
    description: Farbcodes, die im Chat und in deinem Status genutzt werden können
    aliases:
      - colors
  toggleendaccessibility:
    description: ToggleEndAccessibility Command [TEAM ONLY]

  reply:
    description: Antwortet auf eine Nachricht, die an dich per /msg gesendet wurde
    aliases:
      - r
  message:
    description: Sendet eine Nachricht an einen Spieler
    aliases:
      - msg
      - whisper
      - tell
  bounty:
    description: Setzt ein Kopfgeld auf einen Spieler
    aliases:
      - kopfgeld

  spectatestebadon:
    description: hmmmmmmmmmm SuS