name: ProjectPlugin
version: '${project.version}'
main: wtf.melonthedev.projectplugin.Main
api-version: 1.20
authors: [ Melonthedev, Stebadon ]
description: Base plugin for our projects ;)
website: mcsurvivalprojekt.de
softdepend:
  - Log4Minecraft

commands:
  status:
    description: Sets a status in chat and tablist

  position:
    description: Create and list saved positions in the world
    aliases:
      - pos

  colorcodes:
    description: Farbcodes, die im Chat und in deinem Status genutzt werden können
    aliases:
      - colors

  reply:
    description: Antwortet auf eine Nachricht, die an dich per /msg gesendet wurde
    aliases:
      - r

  message:
    description: Sendet eine Nachricht an einen Spieler
    aliases:
      - msg
      - whisper
      - tell

  deathlocation:
    description: Zeigt deine Todesposition an

  checksusplayeractivity:
    description: Check if a player mined suspiciously many ores

  afk:
    description: Just be AFK whenever you want if you dont want to wait

  skippvpcooldown:
    description: Skips the PvP Cooldown

  withdraw:
    description: gib mir herzen

  graveyard:
    description: Sets graveyard positions

  #DEPRECATED
  spectatestebadon:
    description: hmmmmmmmmmm SuS [Deprecated]
  #bounty:
  #  description: Setzt ein Kopfgeld auf einen Spieler
  #  aliases:
  #    - kopfgeld
  #votekick:
  #  description: Votekick Command
  #lockchest:
  #  description: LockChest Command

  #DONATORS ONLY COMMANDS
  weristimnether:
    description: Wer nervt mal wieder beim XP farmen... [Donators]

  #TEAM ONLY COMMANDS
  tempban:
    description: Bans a player temporarily [TEAM ONLY]

  joinmessage:
    description: Sets a joinmessage for a specific player [TEAM ONLY]

  isee:
    description: ISEEEEE YOU [TEAM ONLY]

  hardcore:
    description: Hardcore Settings [TEAM ONLY]

  lifesteal:
    description: Lifesteal Settings [TEAM ONLY]

  survivalprojekt:
    description: SurvivalProjekt Utils [TEAM ONLY]

  pvpcooldown:
    description: PvP Cooldown Settings [TEAM ONLY]

  toggleendaccessibility:
      description: ToggleEndAccessibility Command [TEAM ONLY]

  logoutput:
    description: LogOutput Command [TEAM ONLY]

  donators:
    description: Manage donators server permissions [TEAM ONLY]

  manageplayer:
    description: Manages a specific player [TEAM ONLY]

  timer:
    description: Create and manage a timer [TEAM ONLY]

  velocity:
    description: Gives players velocity [TEAM ONLY]